@extends('layouts.panel')
@section('title', 'ظرفیت و تقویم')
@section('navigation') @include('carwash.partials.navigation') @endsection
@section('content')
<h1 class="mb-6 text-2xl font-bold">ظرفیت و زمان‌بندی</h1>
@can('carwash.schedule.manage')<form method="POST" action="{{ route('carwash.schedule.rules.store',$carWash) }}" class="mb-6 grid gap-3 rounded-2xl bg-white p-5 shadow-sm md:grid-cols-4">@csrf
<select name="weekday" class="rounded-xl border p-3">@foreach(['یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه','شنبه'] as $i=>$day)<option value="{{ $i }}">{{ $day }}</option>@endforeach</select><input type="time" name="start_time" class="rounded-xl border p-3"><input type="time" name="end_time" class="rounded-xl border p-3"><select name="slot_duration_minutes" class="rounded-xl border p-3">@foreach([15,30,45,60,90,120] as $v)<option value="{{ $v }}">{{ $v }} دقیقه</option>@endforeach</select><input type="number" name="capacity" value="1" class="rounded-xl border p-3" placeholder="ظرفیت"><input type="date" name="valid_from" class="rounded-xl border p-3"><input type="date" name="valid_until" class="rounded-xl border p-3"><input type="hidden" name="is_active" value="1"><button class="rounded-xl bg-slate-900 p-3 text-white">افزودن قانون</button></form>@endcan
<div class="mb-6 overflow-x-auto rounded-2xl bg-white shadow-sm"><table class="w-full text-sm"><thead class="bg-slate-100"><tr><th class="p-3">روز</th><th>ساعت</th><th>اسلات</th><th>ظرفیت</th><th>عملیات</th></tr></thead><tbody>@foreach($rules as $rule)<tr class="border-t"><td class="p-3">{{ $rule->weekday }}</td><td>{{ $rule->start_time }} تا {{ $rule->end_time }}</td><td>{{ $rule->slot_duration_minutes }} دقیقه</td><td>{{ $rule->capacity }}</td><td>@can('carwash.schedule.manage')<form method="POST" action="{{ route('carwash.schedule.rules.destroy',[$carWash,$rule]) }}">@csrf @method('DELETE')<button class="text-red-600">حذف</button></form>@endcan</td></tr>@endforeach</tbody></table></div>
@can('carwash.schedule.manage')<form method="POST" action="{{ route('carwash.schedule.exceptions.store',$carWash) }}" class="mb-6 grid gap-3 rounded-2xl bg-white p-5 shadow-sm md:grid-cols-5">@csrf<input type="date" name="exception_date" class="rounded-xl border p-3"><input type="time" name="start_time" class="rounded-xl border p-3"><input type="time" name="end_time" class="rounded-xl border p-3"><input type="number" name="capacity_override" class="rounded-xl border p-3" placeholder="ظرفیت جایگزین"><label class="flex items-center gap-2"><input type="hidden" name="is_closed" value="0"><input type="checkbox" name="is_closed" value="1"> تعطیل</label><input name="reason" class="rounded-xl border p-3 md:col-span-4" placeholder="دلیل"><button class="rounded-xl bg-slate-900 p-3 text-white">ثبت استثنا</button></form>
<form method="POST" action="{{ route('carwash.schedule.regenerate',$carWash) }}" class="mb-6">@csrf<button class="rounded-xl bg-blue-600 px-5 py-3 text-white">بازسازی اسلات‌های آینده</button></form>@endcan
<div class="grid gap-3">@foreach($exceptions as $ex)<div class="flex justify-between rounded-xl bg-white p-4 shadow-sm"><span>{{ $ex->exception_date->format('Y-m-d') }} - {{ $ex->is_closed ? 'تعطیل' : 'ظرفیت '.$ex->capacity_override }} - {{ $ex->reason }}</span>@can('carwash.schedule.manage')<form method="POST" action="{{ route('carwash.schedule.exceptions.destroy',[$carWash,$ex]) }}">@csrf @method('DELETE')<button class="text-red-600">حذف</button></form>@endcan</div>@endforeach</div>
@endsection
