@extends('layouts.panel')
@section('title', 'جزئیات رزرو')
@section('navigation') @include('carwash.partials.navigation') @endsection
@section('content')
<div class="mb-6 flex justify-between"><div><h1 class="text-2xl font-bold">رزرو {{ $booking->tracking_code }}</h1><p class="text-slate-500">{{ $booking->customer_name }} - {{ $booking->customer_mobile }}</p></div><span class="rounded-full bg-blue-50 px-4 py-2">{{ $booking->status->value }}</span></div>
<div class="grid gap-5 lg:grid-cols-2"><div class="rounded-2xl bg-white p-5 shadow-sm"><h2 class="mb-3 font-bold">اطلاعات</h2><p>زمان: {{ $booking->slot->starts_at->timezone($carWash->timezone)->format('Y-m-d H:i') }}</p><p>خودرو: {{ $booking->vehicle_type_snapshot }} - {{ $booking->vehicle_plate_snapshot }}</p><p>مبلغ: {{ number_format($booking->payable_amount) }} ریال</p><p>پرداخت: {{ $booking->payment_status }}</p><div class="mt-3">@foreach($booking->items as $item)<div class="border-t py-2">{{ $item->service_name }} - {{ number_format($item->total_amount) }} ریال</div>@endforeach</div></div>
<div class="rounded-2xl bg-white p-5 shadow-sm"><h2 class="mb-3 font-bold">تغییر وضعیت</h2>@can('carwash.bookings.update')<form method="POST" action="{{ route('carwash.bookings.transition',[$carWash,$booking]) }}" class="space-y-3">@csrf<select name="status" class="w-full rounded-xl border p-3">@foreach(['confirmed','checked_in','in_progress','completed','cancelled','no_show','rejected'] as $s)<option value="{{ $s }}">{{ $s }}</option>@endforeach</select><textarea name="note" class="w-full rounded-xl border p-3" placeholder="توضیح"></textarea><button class="rounded-xl bg-slate-900 px-5 py-3 text-white">ثبت وضعیت</button></form>@endcan</div>
<div class="rounded-2xl bg-white p-5 shadow-sm"><h2 class="mb-3 font-bold">تاریخچه</h2>@foreach($booking->statusHistory as $h)<div class="border-t py-2">{{ $h->from_status ?? '-' }} ← {{ $h->to_status }} | {{ $h->created_at }} | {{ $h->note }}</div>@endforeach</div>
<div class="rounded-2xl bg-white p-5 shadow-sm"><h2 class="mb-3 font-bold">ثبت پرداخت حضوری</h2>@can('carwash.payments.create')<form method="POST" action="{{ route('carwash.payments.store',[$carWash,$booking]) }}" class="space-y-3">@csrf<select name="method" class="w-full rounded-xl border p-3"><option value="cash">نقدی</option><option value="pos">کارت‌خوان</option></select><input type="number" name="amount" value="{{ $booking->payable_amount }}" class="w-full rounded-xl border p-3"><input name="reference_id" class="w-full rounded-xl border p-3" placeholder="شماره مرجع"><button class="rounded-xl bg-emerald-600 px-5 py-3 text-white">ثبت پرداخت</button></form>@endcan</div></div>
@endsection
